name: Build and Deploy BackendApp to ECS

on:
  push:
    branches:
      - main

env:
  ECR_IMAGE: ${{ secrets.ECR_IMAGE }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug AWS region and account
        run: |
          echo "AWS region is: ${{ secrets.AWS_DEFAULT_REGION }}"
          echo "AWS Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Debug ECR login
        run: |
          echo "Logging into AWS ECR with region: ${{ secrets.AWS_DEFAULT_REGION }}"
          echo "Using AWS ECR login URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com"
          echo $password | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Build and push Docker image
        shell: pwsh
        run: |
          Write-Host "ðŸ“¦ Build Docker Ð¾Ð±Ñ€Ð°Ð·Ñƒ..."
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$ECR_IMAGE:latest test_web3_serv/
          Write-Host "ðŸš€ Push Docker Ð¾Ð±Ñ€Ð°Ð·Ñƒ Ð² ECR..."
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$ECR_IMAGE:latest

      - name: Deploy to ECS
        shell: pwsh
        run: |
          Write-Host "ðŸš€ Ð”ÐµÐ¿Ð»Ð¾Ð¹ Ð½Ð° ECS..."
          aws ecs update-service `
            --cluster MpcsjNestJSStabilityIntegration `
            --service MpcsjStabilityAPI `
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
