name: Build and Deploy BackendApp to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest # Використовуємо macOS runner

    env:
      ECR_IMAGE: stablemywebserv
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug AWS region and account
        run: |
          echo "AWS region is: $AWS_DEFAULT_REGION"
          echo "ECR Image name: $ECR_IMAGE"
          echo "AWS Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_DEFAULT_REGION

      - name: Build and push Docker image
        shell: bash
        run: |
          echo "Building Docker image..."
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_IMAGE:latest test_web3_serv/
          echo "Pushing Docker image..."
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_IMAGE:latest

      - name: Deploy to ECS
        run: |
          echo "Deploying to ECS..."
          aws ecs update-service --cluster MpcsjNestJSStabilityIntegration --service MpcsjStabilityAPI --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
